### ISSUE TITLE
Authentication doesn't  work anymore

### ISSUE THREAD

**Issue by Horatio2084** [clarkd/fordpass-python#10]
It looks like the Authentication doesn't work anymore.
Does anyone have the same Problem?

```
Traceback (most recent call last):
  File "/Users/manuel/temp/fordpass-python/fordpass/demo.py", line 17, in <module>
    print(r.status()) # Print the status of the car
  File "/Users/manuel/temp/fordpass-python/fordpass/fordpass.py", line 69, in status
    self.__acquireToken() 
  File "/Users/manuel/temp/fordpass-python/fordpass/fordpass.py", line 61, in __acquireToken
    self.auth()
  File "/Users/manuel/temp/fordpass-python/fordpass/fordpass.py", line 54, in auth
    r.raise_for_status()
  File "/Users/manuel/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fcis.ice.ibmcloud.com/v1.0/endpoint/default/token
```

**Comment by BillyCroan** [comment]
Yep.  Ford intentionally broke it in 2022.  Probably around the same time they cancelled MyFordMobile, or when they started rolling out the 3g to 4g modem updates.  They don't take their platform seriously.  I hope Ford doesn't cancel my steering wheel or air bag license next.

**Comment by bignellrp** [comment]
Same for me. Its a shame as this could have been really handy for custom charging looking up energy rates.

An HTTP error occurred: 400 Client Error: Bad Request for url: https://fcis.ice.ibmcloud.com/v1.0/endpoint/default/token
{"error_description":"The grant type [password] is not supported. Supported grant types are [authorization_code, refresh_token].","error":"unsupported_grant_type"}
