### ISSUE TITLE
defaultHeaders causing invalid syntax error with Python3

### ISSUE THREAD

**Issue by cmaoling** [clarkd/fordpass-python#9]
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from fordpass import Vehicle
  File "/usr/local/lib/python3.4/dist-packages/fordpass/__init__.py", line 1, in <module>
    from .fordpass import Vehicle
  File "/usr/local/lib/python3.4/dist-packages/fordpass/fordpass.py", line 13
    **defaultHeaders,
     ^
SyntaxError: invalid syntax

**Comment by cmaoling** [comment]
Python 3.5 is needed at least to resolve
